# Generated by Django 4.2.7 on 2023-11-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peajes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("idpeaje", models.FloatField(null=True)),
                ("peaje", models.CharField(max_length=500, null=True)),
                ("categoriatarifa", models.FloatField(null=True)),
                ("desde", models.CharField(max_length=500, null=True)),
                ("hasta", models.CharField(max_length=500, null=True)),
                ("valortarifa", models.FloatField(null=True)),
                ("cantidadtrafico", models.FloatField(null=True)),
                ("cantidadevasores", models.FloatField(null=True)),
                ("cantidadexentos787", models.FloatField(null=True)),
                ("anio", models.IntegerField(null=True)),
                ("mes", models.IntegerField(null=True)),
                ("aniomes", models.CharField(max_length=500, null=True)),
                ("recaudo", models.FloatField(null=True)),
            ],
        ),
    ]
